CREATE OR REPLACE VIEW agomarket.vp_tires AS
SELECT
    t.id AS tire_id,
    t.product_id,
    t.dimension_raw,
    t.width,
    t.aspect_ratio,
    t.diameter,
    t.construction,
    t.load_index,
    t.load_index_single,
    t.load_index_dual,
    t.speed_rating,
    t.speed_rating_single,
    t.speed_rating_dual,
    t.tubeless,
    t.tube_type,
    t.ply_rating,
    t.usage,
    t.season,
    t.runflat,
    t.reinforced,
    t.extra_load,
    t.fuel_efficiency,
    t.wet_grip_class,
    t.noise_level,
    t.noise_class,
    t.snow_grip,
    t.ice_grip,
    t.pattern,
    t.tread_depth,
    t.remarks,
    t.created_at,
    t.updated_at
FROM agomarket.tires t;